### ISSUE TITLE
[Bug] kind cluster not building

### ISSUE THREAD

**Issue by kevingigiano** [nishanb/CK-X#20]
Super cool project.

I really want to get it working so here is what I found.

When attempting to start an exam, the kind cluster never gets built.

Here is what I see in the logs:
```
kind-cluster       | /usr/local/bin/env-setup: line 55: k3d: not found
kind-cluster       | 2025-04-17 17:58:29 | Verifying cluster status...
kind-cluster       | /usr/local/bin/env-setup: line 65: k3d: not found
```

I exec'd into the kind-cluster container and confirmed k3d and k3s were not installed.
I was able to move past the error with the following:
```
# install k3s
apk add k3s

# install k3d
curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

# create k3d cluster
k3d cluster create --config /tmp/k3d-config.yaml
```

After getting past the error above, the exam never finishes launching.

![Image](https://github.com/user-attachments/assets/29b06a80-083e-47cb-9e6d-5f69733e0031)

logs just keep showing:

![Image](https://github.com/user-attachments/assets/4a455d60-0cea-43a6-a49a-58a8b20f69cc)

This is running on a Cent9.5 box.

Any help would be appreciated.
Thanks,
Kevin

**Comment by nishanb** [comment]
Hi @kevingigiano , can you please try to run it using a quick installation command. Where it pulls & runs the pre built images , meanwhile I'll try to fix this

**Comment by nishanb** [comment]
Can you also provide full log Along with system information os, arch ... and how are you building and running it

**Comment by kevingigiano** [comment]
This is how I initially did the install:
`curl -fsSL https://raw.githubusercontent.com/nishanb/ck-x/master/scripts/install.sh | bash`

Log file is attached.

OS:
CentOS Stream 9

**Comment by nishanb** [comment]
Hey @kevingigiano looks like docker-in-docker isn't starting properly. 
"kind-cluster      | Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" 

can you please try running dind `docker run --rm --privileged docker:dind`, once started check status of docker using `docker ps`

since docker isn't starting k3d is not downloaded, will add a check for this in the code. if possible can you share output of `docker info`  will help to resolve

**Comment by nishanb** [comment]
> Hey [@kevingigiano](https://github.com/kevingigiano) looks like docker-in-docker isn't starting properly. "kind-cluster | Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
> 
> can you please try running dind `docker run --rm --privileged docker:dind`, once started check status of docker using `docker ps`
> 
> since docker isn't starting k3d is not downloaded, will add a check for this in the code. if possible can you share output of `docker info` will help to resolve

also try running installation script as sudo

**Comment by nishanb** [comment]
> Super cool project.
> 
> I really want to get it working so here is what I found.
> 
> When attempting to start an exam, the kind cluster never gets built.
> 
> Here is what I see in the logs:
> 
> ```
> kind-cluster       | /usr/local/bin/env-setup: line 55: k3d: not found
> kind-cluster       | 2025-04-17 17:58:29 | Verifying cluster status...
> kind-cluster       | /usr/local/bin/env-setup: line 65: k3d: not found
> ```
> 
> I exec'd into the kind-cluster container and confirmed k3d and k3s were not installed. I was able to move past the error with the following:
> 
> ```
> # install k3s
> apk add k3s
> 
> # install k3d
> curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
> 
> # create k3d cluster
> k3d cluster create --config /tmp/k3d-config.yaml
> ```
> 
> After getting past the error above, the exam never finishes launching.
> 
> ![Image](https://github.com/user-attachments/assets/29b06a80-083e-47cb-9e6d-5f69733e0031)
> 
> logs just keep showing:
> 
> ![Image](https://github.com/user-attachments/assets/4a455d60-0cea-43a6-a49a-58a8b20f69cc)
> 
> This is running on a Cent9.5 box.
> 
> Any help would be appreciated. Thanks, Kevin

resolved in #24

**Comment by kevingigiano** [comment]
Sorry for not responding sooner.

Running the install script as root doesn't make a difference.

Part of my issue is my docker setup.
I expose docker on my dev machine for other build purposes.
Once I accounted for that, I update k8s-api-server section of my docker compose:
```
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.17.0.1:2375/_ping"]
      interval: 30s
      timeout: 5s
      retries: 20
      start_period: 60s
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
```

I still have the issue where k3s and k3d are not deployed to the kind-cluster container.

I don't know if this is contributing to my issues, but I run CentOS as a virtual machine, running on VMware workstation, on a Win10 host.
